import pandas as pd
from ..pyaugsynth import dataprep


df = pd.read_csv("../data/smoking.csv")

out = dataprep(
    foo=df,
    predictors=("lnincome", "beer", "age15to24", "retprice"),
    predictors_op="mean",
    time_predictors_prior=range(1970, 1989),
    special_predictors=(
        ("lnincome", range(1980, 1989), "mean"),
        ("retprice", range(1980, 1989), "mean"),
        ("age15to24", range(1980, 1989), "mean"),
        ("beer", range(1984, 1989), "mean"),
        ("cigsale", [1975], "mean"),
        ("cigsale", [1980], "mean"),
        ("cigsale", [1988], "mean"),
    ),
    dependent="cigsale",
    unit_variable="state",
    time_variable="year",
    treatment_identifier="California",
    controls_identifier=(
        "Alabama",
        "Arkansas",
        "Colorado",
        "Connecticut",
        "Delaware",
        "Georgia",
        "Idaho",
        "Illinois",
        "Indiana",
        "Iowa",
        "Kansas",
        "Kentucky",
        "Louisiana",
        "Maine",
        "Minnesota",
        "Mississippi",
        "Missouri",
        "Montana",
        "Nebraska",
        "Nevada",
        "New Hampshire",
        "New Mexico",
        "North Carolina",
        "North Dakota",
        "Ohio",
        "Oklahoma",
        "Pennsylvania",
        "Rhode Island",
        "South Carolina",
        "South Dakota",
        "Tennessee",
        "Texas",
        "Utah",
        "Vermont",
        "Virginia",
        "West Virginia",
        "Wisconsin",
        "Wyoming",
    ),
    time_optimize_ssr=range(1970, 1989),
    time_plot=range(1970, 2001),
)
