import unittest
import pandas as pd

from pysyncon import Dataprep, AugSynth


class TestAugsynthBasque(unittest.TestCase):
    def setUp(self):
        df = pd.read_csv("./data/basque.csv")
        self.dataprep = Dataprep(
            foo=df,
            predictors=[
                "school.illit",
                "school.prim",
                "school.med",
                "school.high",
                "school.post.high",
                "invest",
            ],
            predictors_op="mean",
            time_predictors_prior=range(1964, 1970),
            special_predictors=[
                ("gdpcap", range(1960, 1970), "mean"),
                ("sec.agriculture", range(1961, 1970, 2), "mean"),
                ("sec.energy", range(1961, 1970, 2), "mean"),
                ("sec.industry", range(1961, 1970, 2), "mean"),
                ("sec.construction", range(1961, 1970, 2), "mean"),
                ("sec.services.venta", range(1961, 1970, 2), "mean"),
                ("sec.services.nonventa", range(1961, 1970, 2), "mean"),
                ("popdens", [1969], "mean"),
            ],
            dependent="gdpcap",
            unit_variable="regionname",
            time_variable="year",
            treatment_identifier="Basque Country (Pais Vasco)",
            controls_identifier=[
                "Andalucia",
                "Aragon",
                "Baleares (Islas)",
                "Canarias",
                "Cantabria",
                "Castilla-La Mancha",
                "Castilla Y Leon",
                "Cataluna",
                "Comunidad Valenciana",
                "Extremadura",
                "Galicia",
                "Madrid (Comunidad De)",
                "Murcia (Region de)",
                "Navarra (Comunidad Foral De)",
                "Principado De Asturias",
                "Rioja (La)",
                "Spain (Espana)",
            ],
            time_optimize_ssr=range(1955, 1970),
        )
        # Regression baseline generated by the corrected (ported) algorithm
        # on 2026-09-03. The algorithm is verified against the published
        # outputs of the R augsynth package for the Kansas example (see
        # test_augsynth_kansas.py); these basque values are not independently
        # R-verified.
        self.weights = {
            "Andalucia": -0.018427858,
            "Aragon": -0.794911715,
            "Baleares (Islas)": -0.266161176,
            "Canarias": 0.691017465,
            "Cantabria": 0.449422093,
            "Castilla-La Mancha": 0.088892476,
            "Castilla Y Leon": -0.55864735,
            "Cataluna": 1.036152892,
            "Comunidad Valenciana": -0.796111965,
            "Extremadura": -0.259062786,
            "Galicia": 0.42387125,
            "Madrid (Comunidad De)": 0.065377596,
            "Murcia (Region de)": -0.341446337,
            "Navarra (Comunidad Foral De)": 0.40377683,
            "Principado De Asturias": 0.270530718,
            "Rioja (La)": 0.630628696,
            "Spain (Espana)": -0.024900828,
        }

    def test_weights(self):
        augsynth = AugSynth()
        augsynth.fit(dataprep=self.dataprep)

        weights = pd.Series(self.weights, name="weights")
        pd.testing.assert_series_equal(
            weights, augsynth.weights(round=9), check_exact=False, atol=0.025
        )
