name: Generate Code Coverage report and upload to codecov.io

on:
  pull_request:
    branches: main
    paths:
      - "pysyncon/**"
      - "tests/**"
  push:
    branches: main
    paths:
      - "pysyncon/**"
      - "tests/**"

permissions:
  contents: read

jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-dev.txt
          python -m pip install codecov
      - name: Run tests and collect coverage
        run: coverage run -m unittest discover -s tests
      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v4.2.0
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
